apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: dssp-test-28-04
  description: Service dssp-test-28-04

  annotations:
    github.com/project-slug: BackstageSSPPoC/dssp-test-28-04
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: Backstage_SSP_PoC/dssp-test-28-04/main
    argocd/app-name: dssp-test-28-04
    backstage.io/kubernetes-id: dssp-test-28-04
    backstage.io/kubernetes-namespace: default
    sonarqube.org/project-key: dssp-test-28-04

spec:
  type: service
  owner: development
  lifecycle: experimental
